language: cpp
sudo: required
services:
    - docker
cache:
    directories:
        - $HOME/.ccache
        - $HOME/Library/Caches/Homebrew
matrix:
    include:
#        - env: TYPE=style
#        - env: IMAGE_NAME=ubuntu-linux-gcc IMAGE_TAG=14.04
#        - env: IMAGE_NAME=ubuntu-mingw-w32 IMAGE_TAG=14.04 TARGET_OS=win32
#        - env: IMAGE_NAME=ubuntu-mingw-w64 IMAGE_TAG=14.04 TARGET_OS=win64
        - env: IMAGE_NAME=ubuntu-linux-gcc IMAGE_TAG=18.04
#        - env: IMAGE_NAME=ubuntu-mingw-w32 IMAGE_TAG=18.04 TARGET_OS=win32
#        - env: IMAGE_NAME=ubuntu-mingw-w64 IMAGE_TAG=18.04 TARGET_OS=win64
#        - os: osx
          osx_image: xcode8.3
install: ${TRAVIS_BUILD_DIR}/.travis/install.sh
script: ${TRAVIS_BUILD_DIR}/.travis/script.sh
after_script: ${TRAVIS_BUILD_DIR}/.travis/after_script.sh
before_deploy: make package
deploy:
    provider: releases
    api_key:
        secure: d4a+x4Gugpss7JK2DcHjyBZDmEFFh4iVfKDfITSD50T6Mc6At4LMgojvEu+6qT6IyOY2vm3UVT6fhyeuWDTRDwW9tfFlaHVA0h8aTRD+eAXOA7pQ8rEMwQO3+WCKuKTfEqUkpL4wxhww8dpkv54tqeIs0S4TBqz9tk8UhzU7XbE=
    file: lmms-${TRAVIS_TAG:1}-$TARGET_OS.exe
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
        condition: '("$TARGET_OS" = win??)'
    repo: LMMS/lmms
env:
  global:
    secure: ePyXi4i8tMGQ2SSFCgI5J3uF2ctq2o60gMgzByRYTSYs9REM3t4IRbT8CInWF3Te5VfJC3SipyhF9nLpeSlZr6qZ8VNipLfiz5CWRKlzs074wpnI+RaTGT91y4fssEQd0Yf5izU+E4FIpXMqh5lP3M0OGUoZF+0v/544mrpJIVY=
