version: 2

shared:
  restore_ccache: &restore_ccache
    restore_cache:
      keys:
        - ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
        - ccache-{{ .Environment.CIRCLE_JOB }}
        - ccache
  save_ccache: &save_ccache
    save_cache:
      key: ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .BuildNum }}
      paths:
        - ~/.ccache

  ccache_stats: &ccache_stats
    run:
      name: Print ccache statistics
      command: |
        echo "[ccache config]"
        ccache -p
        echo "[ccache stats]"
        ccache -s

  # Commmon initializing commands
  init: &init
    run:
      name: Initialize
      command: |
        mkdir -p /tmp/artifacts

  # Commmon environment variables
  common_environment: &common_environment
    QT5: True
    CMAKE_OPTS: -DUSE_WERROR=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_CCACHE=ON
    CCACHE_MAXSIZE: 500M
    CCACHE_LOGFILE: /tmp/artifacts/ccache.log
    MAKEFLAGS: -j6

  common: &common
    docker:
      - image: lukaswhl/docker
    steps:
      - *init
      - *restore_ccache
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            .travis/linux.install.sh
      - run:
          name: Build LMMS
          command: |
            mkdir build
            .travis/linux.script.sh
      - *ccache_stats
      - *save_ccache

jobs:
  linux-gcc:
    <<: *common
    environment:
      <<: *common_environment
      IMAGE_NAME: ubuntu-linux-gcc
      IMAGE_TAG: 14.04
workflows:
  version: 2
  build-and-test:
    jobs:
      - linux-gcc
